// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsLqbJqkRezXQhkopnnz74dR2_t9yTSFI',
    appId: '1:541776774390:web:05835913320fcedfe8d8d7',
    messagingSenderId: '541776774390',
    projectId: 'authentication-bloc-firebase-2',
    authDomain: 'authentication-bloc-firebase-2.firebaseapp.com',
    storageBucket: 'authentication-bloc-firebase-2.firebasestorage.app',
    measurementId: 'G-RPV8FFTEZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAp5sLPlIbvAT2raSYz9k1tZ07-MRv9Q4',
    appId: '1:541776774390:android:691d5f838a0c730ae8d8d7',
    messagingSenderId: '541776774390',
    projectId: 'authentication-bloc-firebase-2',
    storageBucket: 'authentication-bloc-firebase-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDszV_ZDjbPw9Cgx3Ee25gmH-wdE9yzBqE',
    appId: '1:541776774390:ios:b101810c2b88970fe8d8d7',
    messagingSenderId: '541776774390',
    projectId: 'authentication-bloc-firebase-2',
    storageBucket: 'authentication-bloc-firebase-2.firebasestorage.app',
    iosBundleId: 'com.example.authenticationBlocFirebase2',
  );
}
